# Variables passed to this playbook:
# -         'etcdadd': list of instances that'll be added to the etcd cluster.
# -         'nodeadd': list of instances that'll be added to the node category.
# -         'masteradd': list of instances that'll be added to the master category.
# Note: This playbook is called *PRIOR* to OpenShift installation on new instances.
---
- hosts: all
  tasks:
  - debug:
      msg: running pre-scaleup for all
- hosts: masters
  tasks:
  - debug:
      msg: running pre-scaleup for masters
    when: masteradd | length > 0
- hosts: etcd
  tasks:
  - debug:
      msg: running pre-scaleup for etcd
    when: etcdadd | length > 0
- hosts: nodes
  tasks:
  - debug:
      msg: running pre-scaleup for nodes
    when: nodeadd | length > 0
  - name: Wait until the file /tmp/bootstrapped is present before continuing
    wait_for:
      path: /tmp/bootstrapped
      timeout: 600
